### ISSUE TITLE
from-emitter.js: TypeError: read is not a function

### ISSUE THREAD

**Issue by cryptix** [nichoth/pull-stream-util#1]
This package looks very useful. I want to entangle the stdio<>readline<>eventEmitter madness of [forked-systray](https://github.com/ssbc/forked-systray/blob/master/src/index.ts) with it but ran into this using the `from-emitter.js` example:

```
/home/cryptix/ssb/pull-stream-util/node_modules/pull-stream/sinks/drain.js:16
          read(null, function (end, data) {
          ^

TypeError: read is not a function
    at next (/home/cryptix/ssb/pull-stream-util/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/home/cryptix/ssb/pull-stream-util/node_modules/pull-stream/sinks/drain.js:37:9)
    at pull (/home/cryptix/ssb/pull-stream-util/node_modules/pull-stream/pull.js:41:14)
    at Object.<anonymous> (/home/cryptix/ssb/pull-stream-util/example/from-emitter.js:8:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by cryptix** [comment]
no rush. I worked it using a different construction.
